name: libadvent
version: 0.2.0.18
ghc-options: -Wall -fwarn-tabs -fwarn-incomplete-record-updates -fwarn-monomorphism-restriction -fwarn-unused-do-bind
dependencies:
  - base
  - containers
  - pureMD5
  - mtl
  - megaparsec
  - bytestring

library:
  exposed-modules:
    - Advent.Library
    - Advent.Library.Trie
  source-dirs: src